eureka:
  client:
    region: default
    registryFetchIntervalSeconds: '5'
logging:
  level:
    org:
      springframework:
        web: debug
spring:
  application:
    name: zipkin-server
server:
  port: '9411'
