spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/productservice
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'false'
        use_sql_comments: 'true'
    show-sql: 'false'
    hibernate:
      ddl-auto: update

server:
  port: 8010

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka